### ISSUE TITLE
[Feature] Improve clarity on step 2

### ISSUE THREAD

**Issue by Deselikem** [skills/continuous-integration#10]
**Is your feature request related to a problem? Please describe.**
hard to understand what is meant in the image below 

![image](https://user-images.githubusercontent.com/91301618/175648833-bec57225-c0a6-4958-ad49-a5c4d6ffb773.png)

**Comment by ProDataMan** [comment]
yes what does that mean?  in the instructions it says to update the code in the ci branch.   what code?  what are you supposed to update? you need to look for something like _underscore_ look for it where? look for that text literally? The only place I was able to find that text was in the readme.md file that I was reading it in.

**Comment by sinsukehlab** [comment]
Check the error in the ci.yml build and you will find a helpful warning message.

**Comment by thongonary** [comment]
The instruction should have explained what the installed packages do
https://unifiedjs.com/explore/package/remark-lint-emphasis-marker/
>This package is a [unified](https://unifiedjs.com/explore/package/unified/) ([remark](https://unifiedjs.com/explore/project/remarkjs/remark/)) plugin, specifically a remark-lint rule. Lint rules check markdown code style.
You can use this package to check that emphasis markers are consistent.

This would make it way less confusing.

**Comment by sinsukehlab** [comment]
Step 0 contains a link to the remark-lint GitHub repository, but is commented out by 0-start.yml.

**Comment by MathElderGod** [comment]
look at the read me, line 115. The libraries cause rules to be implemented based on emphasis...I was stuck on this for about 1:30 hour

**Comment by ted-repo** [comment]
Still trying to figure out the solution on how to complete this activity **Fix the test**

Anyone with more direct guidance? thanks,

**Comment by sinsukehlab** [comment]
Go to the Actions tab and check the error.
Follow the warning message.

```
found 0 vulnerabilities
README.md
  115:1-115:63  warning  Emphasis should use `_` as a marker  emphasis-marker  remark-lint

⚠ 1 warning
Error: Process completed with exit code 1.
```

**Comment by AndylLow** [comment]
For anyone stuck at this step:
Go to line 115 in readme and change both "*" into "_".

**Comment by k-byun** [comment]
still stuck.  Action workflow screenshot shown just before line 115 doesn't look like what I am seeing on my workflow (ie, I don't see "Review required", the first big :x:)

**Comment by leonfeng** [comment]
If you're not seeing the `❌ Some checks didn't pass` message, chances are you left extra lines in the workflow file.

Go back to Step 1, Task 6. Open `ci.yml` and delete everything from line 28 to EOF. Now the last non-blank line in your file should read `- uses: actions/checkout@v3`. Continue with Task 7 and add the markdown lint step.

If that doesn't help, try deleting the repo and starting over.

**Comment by ndagisusan** [comment]
Thank you @leonfeng and @AndylLow for your solutions.
This has finally worked for me 🙏
