### ISSUE TITLE
[Bug] Step 2 won't open in the `main` branch

### ISSUE THREAD

**Issue by sinsukehlab** [skills/continuous-integration#20]
**Describe the bug**
Step 2 won't open in the 'main' branch.

**To Reproduce**
1. Go to Step1
2. Complete the Activity
3. Refresh after ~20 seconds

**Expected behavior**
Step 2 opens both in the `main` and `ci` branch.

**Screenshots**

**Device information**
 - Type: [e.g. iPhone6]

**Additional context**

**Comment by sinsukehlab** [comment]
I will close this issue once the patch (bb17983 on skills/action-update-step) is released as v1.2.1.

**Comment by sinsukehlab** [comment]
Now that skills/action-update-step@v1.2.1 is released, I will check the actions again.

**Comment by heiskr** [comment]
Thanks for opening this issue. I believe this problem has been resolved, but let us know if the issue persists.
