### ISSUE TITLE
[Bug] 2-fix-the-test.yml triggers on the wrong file.

### ISSUE THREAD

**Issue by gsacavdm** [skills/continuous-integration#28]
**Describe the bug**
Completing "Step 2: Fix the test" doesn't result in the Step 3 being opened in the README.

This is because the `2-fix-the-test.yml` workflow is looking for push on `README.md` however the test is failing because of a lint error in `resume.md`:

<img width="805" alt="image" src="https://user-images.githubusercontent.com/3582236/220834365-7418528e-be4b-4337-a813-45d353ba450b.png">

**Comment by gsacavdm** [comment]
I was going to submit a PR for this but I can't figure out how to submit a PR from my generated repo.

Here's the [commit](https://github.com/gsacavdm/continuous-integration/commit/9661f62ccc1818712ee50d9e5cb748da87ec3b16) and the change:
<img width="809" alt="image" src="https://user-images.githubusercontent.com/3582236/220837667-231a4d46-c3eb-4b8c-af1b-ff08d835d117.png">

**Comment by heiskr** [comment]
Thanks for opening this issue! We may not have tested as thoroughly as we should have here, I apologize for that. I'll get this updated.
