### ISSUE TITLE
[Bug] Step 1.3 Search for "Simple workflow".

### ISSUE THREAD

**Issue by liam-parker-risk** [skills/continuous-integration#7]
**Describe the bug**
Step 1.3 Search for "Simple workflow" isn't visible in the Actions tab until clicking New Workflow.  This wasn't obvious (at least to me) and isn't mentioned in the write up.

**To Reproduce**
1. Try to follow the steps described in Step 1

**Expected behavior**
Step 3 could read : Click new workflow and then search for "Simple workflow"

**Comment by parroty** [comment]
Hi. I think I noticed the same mismatch and submitted the following PR. Does this resolve your concern?
- https://github.com/skills/continuous-integration/pull/6

**Comment by heiskr** [comment]
I believe this issue was resolved by https://github.com/skills/continuous-integration/pull/6/files, but let us know if the issue persists.
